// AMAANAT MEDICAL — Shared Tailwind Configuration
// Generated from Stitch DESIGN.md: "Clinical Engineering Precision"
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface":                    "#f8f9ff",
        "surface-dim":                "#cbdbf5",
        "surface-bright":             "#f8f9ff",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#eff4ff",
        "surface-container":          "#e5eeff",
        "surface-container-high":     "#dce9ff",
        "surface-container-highest":  "#d3e4fe",
        "on-surface":                 "#0b1c30",
        "on-surface-variant":         "#42474e",
        "inverse-surface":            "#213145",
        "inverse-on-surface":         "#eaf1ff",
        "outline":                    "#72777e",
        "outline-variant":            "#c2c7ce",
        "surface-tint":               "#396285",
        "primary":                    "#00263f",
        "on-primary":                 "#ffffff",
        "primary-container":          "#0b3c5d",
        "on-primary-container":       "#7fa7cd",
        "inverse-primary":            "#a3cbf2",
        "primary-fixed":              "#cee5ff",
        "primary-fixed-dim":          "#a3cbf2",
        "on-primary-fixed":           "#001d32",
        "on-primary-fixed-variant":   "#1f4a6c",
        "secondary":                  "#006783",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#70d6fe",
        "on-secondary-container":     "#005c75",
        "secondary-fixed":            "#bce9ff",
        "secondary-fixed-dim":        "#6dd3fb",
        "on-secondary-fixed":         "#001f29",
        "on-secondary-fixed-variant": "#004d63",
        "tertiary":                   "#002a1f",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#004233",
        "on-tertiary-container":      "#57b397",
        "tertiary-fixed":             "#98f4d5",
        "tertiary-fixed-dim":         "#7cd8ba",
        "on-tertiary-fixed":          "#002118",
        "on-tertiary-fixed-variant":  "#00513f",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "background":                 "#f8f9ff",
        "on-background":              "#0b1c30",
        "surface-variant":            "#d3e4fe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        xs:             "4px",
        sm:             "12px",
        base:           "8px",
        md:             "24px",
        lg:             "48px",
        xl:             "80px",
        gutter:         "24px",
        "container-max":"1280px",
      },
      fontFamily: {
        h1:           ["Inter"],
        h2:           ["Inter"],
        h3:           ["Inter"],
        button:       ["Inter"],
        "label-caps": ["Inter"],
        "body-lg":    ["Open Sans"],
        "body-md":    ["Open Sans"],
        "body-sm":    ["Open Sans"],
      },
      fontSize: {
        h1:           ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2:           ["36px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3:           ["24px", { lineHeight: "1.4", letterSpacing: "0",       fontWeight: "600" }],
        button:       ["14px", { lineHeight: "1",   letterSpacing: "0.01em",  fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1",   letterSpacing: "0.05em",  fontWeight: "700" }],
        "body-lg":    ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":    ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm":    ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
};
